import { NextRequest, NextResponse } from 'next/server';
import { checkAdminSession, getLiveAdminPermissions, isPMEmail } from '@/lib/admin-auth';
import { createAdminClient } from '@/lib/supabase';

export async function GET(req: NextRequest) {
  try {
    const session = await checkAdminSession();
    if (!session) return NextResponse.json({ success: false, message: 'Unauthorized' }, { status: 401 });

    const isPM = session.role === 'PROJECT_MANAGER' || isPMEmail(session.email);

    // Dynamic Permission Check: If not PM, verify user has audit_logs permission
    if (!isPM) {
      const livePerms = await getLiveAdminPermissions(session.id);
      if (!livePerms.audit_logs) {
        return NextResponse.json({ success: false, message: 'Access denied: Audit logs permission required' }, { status: 403 });
      }
    }

    const { searchParams } = new URL(req.url);
    const actionType = searchParams.get('action') || 'all';
    const search = searchParams.get('search') || '';
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '50');
    const offset = (page - 1) * limit;

    const supabase = createAdminClient();

    let query = supabase
      .from('audit_logs')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false });

    // STEALTH FILTER: If caller is not PM, hide stealth passes and internal PM operations
    if (!isPM) {
      // 1. Hide any log marked with is_stealth or created_by_pm
      query = query.or('details->>is_stealth.is.null,details->>is_stealth.eq.false');
      query = query.or('details->>created_by_pm.is.null,details->>created_by_pm.eq.false');

      // 2. Hide PM administrative internal actions (permission updates, logins, etc.)
      // Normal pass manual entries generated by PM remain visible to authorized admins
      const pmEmails = ['muhammadarham979@gmail.com', 'arham.personal28@gmail.com'];
      for (const email of pmEmails) {
        query = query.or(`performed_by.not.ilike.%${email}%,action_type.eq.manual_entry_created`);
      }
    }

    query = query.range(offset, offset + limit - 1);

    if (actionType !== 'all') {
      query = query.eq('action_type', actionType);
    }

    if (search) {
      query = query.or(`roll_no.ilike.%${search}%,student_name.ilike.%${search}%,performed_by.ilike.%${search}%`);
    }

    const { data: logs, count, error } = await query;
    if (error) throw error;

    // Get count for double scans specifically (Security Update #3)
    const { count: doubleScansCount } = await supabase
      .from('audit_logs')
      .select('*', { count: 'exact', head: true })
      .eq('action_type', 'double_scan_forced');

    return NextResponse.json({
      success: true,
      logs: logs || [],
      total: count || 0,
      stats: {
        double_scans: doubleScansCount || 0,
      },
    });
  } catch (err) {
    console.error('Audit logs API error:', err);
    return NextResponse.json({ success: false, message: 'Server error' }, { status: 500 });
  }
}
