import { NextRequest, NextResponse } from 'next/server';
import { checkAdminSession, isPMEmail } from '@/lib/admin-auth';
import { createAdminClient } from '@/lib/supabase';
import { getQuotaStatus, processEmailQueue, recordDirectEmailSent, recordEmailsSent, resetHourlyQuota } from '@/lib/email-queue';
import { updateSystemSettings } from '@/lib/system-settings';
import { sendEmailWithFailover } from '@/lib/email-service';
import { logAuditEvent } from '@/lib/audit';

export async function GET(req: NextRequest) {
  try {
    const session = await checkAdminSession();
    if (!session) return NextResponse.json({ success: false, message: 'Unauthorized' }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const status = searchParams.get('status') || 'all';
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '50');
    const offset = (page - 1) * limit;

    const quota = await getQuotaStatus();
    const supabase = createAdminClient();

    let query = supabase
      .from('email_queue')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (status !== 'all') {
      query = query.eq('status', status);
    }

    const { data: rawItems, count, error } = await query;
    if (error) throw error;

    const isPM = session.role === 'PROJECT_MANAGER' || isPMEmail(session.email);

    // Attach pass_status and filter out/purge permanently deleted passes
    const rollNos = Array.from(new Set((rawItems || []).map((i) => i.roll_no).filter(Boolean)));
    const qrTokens = Array.from(new Set((rawItems || []).map((i) => i.qr_token).filter(Boolean)));

    const passStatusByRoll = new Map<string, string>();
    const passStatusByQr = new Map<string, string>();
    const isPmPassByRoll = new Map<string, boolean>();
    const isPmPassByQr = new Map<string, boolean>();

    if (rollNos.length > 0 || qrTokens.length > 0) {
      const orClauses: string[] = [];
      if (rollNos.length > 0) {
        orClauses.push(`roll_no.in.(${rollNos.map((r) => `"${r}"`).join(',')})`);
      }
      if (qrTokens.length > 0) {
        orClauses.push(`qr_token.in.(${qrTokens.map((t) => `"${t}"`).join(',')})`);
      }

      const { data: passes } = await supabase
        .from('approved_passes')
        .select('roll_no, qr_token, pass_status, created_by_pm')
        .or(orClauses.join(','));

      if (passes) {
        for (const p of passes) {
          if (p.roll_no) {
            passStatusByRoll.set(p.roll_no.toLowerCase(), p.pass_status || 'generated');
            if (p.created_by_pm) isPmPassByRoll.set(p.roll_no.toLowerCase(), true);
          }
          if (p.qr_token) {
            passStatusByQr.set(p.qr_token, p.pass_status || 'generated');
            if (p.created_by_pm) isPmPassByQr.set(p.qr_token, true);
          }
        }
      }
    }

    const items: any[] = [];
    const orphanIds: string[] = [];

    for (const item of (rawItems || [])) {
      const normRoll = (item.roll_no || '').toLowerCase();
      const statusFromRoll = passStatusByRoll.get(normRoll);
      const statusFromQr = item.qr_token ? passStatusByQr.get(item.qr_token) : undefined;
      const passStatus = statusFromRoll || statusFromQr;
      const isPmPass = Boolean(isPmPassByRoll.get(normRoll) || (item.qr_token && isPmPassByQr.get(item.qr_token)) || item.metadata?.created_by_pm);

      // STEALTH: If not PM and pass was generated by PM, hide from queue
      if (!isPM && isPmPass) {
        continue;
      }

      if (!passStatus) {
        // Pass was permanently deleted from approved_passes!
        orphanIds.push(item.id);
      } else {
        items.push({
          ...item,
          pass_status: passStatus,
          created_by_pm: isPmPass,
        });
      }
    }

    // Purge orphaned items in background
    if (orphanIds.length > 0) {
      supabase.from('email_queue').delete().in('id', orphanIds).then(() => {});
    }

    // Get count breakdown
    const { count: totalQueued } = await supabase.from('email_queue').select('*', { count: 'exact', head: true }).eq('status', 'queued');
    const { count: totalSent } = await supabase.from('email_queue').select('*', { count: 'exact', head: true }).eq('status', 'sent');
    const { count: totalFailed } = await supabase.from('email_queue').select('*', { count: 'exact', head: true }).eq('status', 'failed');

    return NextResponse.json({
      success: true,
      quota,
      stats: {
        queued: totalQueued || 0,
        sent: totalSent || 0,
        failed: totalFailed || 0,
      },
      items,
      total: count || 0,
      is_pm: isPM,
    });
  } catch (err) {
    console.error('Email queue API error:', err);
    return NextResponse.json({ success: false, message: 'Server error' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const session = await checkAdminSession();
    if (!session) return NextResponse.json({ success: false, message: 'Unauthorized' }, { status: 401 });

    const isPM = session.role === 'PROJECT_MANAGER' || isPMEmail(session.email);
    const body = await req.json().catch(() => ({}));
    const { action, id, to_email } = body;

    if (action === 'toggle_hourly_override') {
      if (!isPM) {
        return NextResponse.json({ success: false, message: 'Access denied: Project Manager only' }, { status: 403 });
      }
      const { enabled } = body;
      await updateSystemSettings({ hourly_email_override: Boolean(enabled) }, session.email);
      const updatedQuota = await getQuotaStatus();
      return NextResponse.json({
        success: true,
        message: enabled
          ? '⚡ Hourly limit override ENABLED (Capacity expanded to 550/day)!'
          : 'Hourly limit restored to standard (70 emails/hour)',
        quota: updatedQuota,
      });
    }

    if (action === 'reset_hourly_quota') {
      if (!isPM) {
        return NextResponse.json({ success: false, message: 'Access denied: Project Manager only' }, { status: 403 });
      }
      await resetHourlyQuota();
      await logAuditEvent({
        action_type: 'setting_changed',
        performed_by: session.email,
        user_role: session.role,
        details: { action: 'reset_hourly_quota', reset_by: session.email },
      });
      const updatedQuota = await getQuotaStatus();
      return NextResponse.json({
        success: true,
        message: 'Current hour quota counter reset to 0.',
        quota: updatedQuota,
      });
    }

    if (action === 'retry' && id) {
      const supabase = createAdminClient();
      const { error } = await supabase
        .from('email_queue')
        .update({ status: 'queued', error_message: null })
        .eq('id', id);

      if (error) throw error;
      return NextResponse.json({ success: true, message: 'Email queued for retry' });
    }

    if (action === 'process_now') {
      const batchSize = typeof body.batch_size === 'number' ? body.batch_size : 70;
      const result = await processEmailQueue(batchSize);
      return NextResponse.json({
        success: true,
        message: `Processed ${result.processed} emails (${result.failed} failed).`,
        result,
      });
    }

    if (action === 'test_send') {
      const targetEmail = to_email || session.email;
      if (!targetEmail || !targetEmail.includes('@')) {
        return NextResponse.json({ success: false, message: 'Valid recipient email required' }, { status: 400 });
      }

      const htmlContent = `
        <div style="font-family:'Inter',Arial,sans-serif;max-width:540px;margin:0 auto;background:#0f172a;border-radius:16px;overflow:hidden;color:#ffffff;padding:24px;border:1px solid #334155;">
          <h2 style="color:#60a5fa;margin-top:0;">⚡ Live Email Diagnostic Test</h2>
          <p style="color:#cbd5e1;font-size:14px;">This is a real-time diagnostic test from the Fresher Party Scanner Admin Panel.</p>
          <div style="background:#1e293b;border-radius:8px;padding:12px 16px;margin:16px 0;font-size:13px;color:#94a3b8;">
            <p style="margin:4px 0;"><strong>Sender:</strong> System Email Service</p>
            <p style="margin:4px 0;"><strong>Recipient:</strong> ${targetEmail}</p>
            <p style="margin:4px 0;"><strong>Timestamp:</strong> ${new Date().toISOString()}</p>
          </div>
          <p style="color:#10b981;font-size:13px;font-weight:600;">✅ Brevo API Connection Verified & Active!</p>
        </div>
      `;

      const sendResult = await sendEmailWithFailover(
        targetEmail,
        '🧪 Fresher Party System: Live Diagnostic Test Email',
        htmlContent
      );

      if (sendResult.status === 'failed') {
        return NextResponse.json({ success: false, message: `Send failed: ${sendResult.message}` }, { status: 502 });
      }

      await recordEmailsSent(1, sendResult.apiUsed || 'primary');

      await recordDirectEmailSent({
        student_name: session.name || 'System Admin',
        email: targetEmail,
        roll_no: 'DIAG-TEST',
        department: 'Admin Diagnostic',
        batch: '2026',
        society: 'System',
      });

      await logAuditEvent({
        action_type: 'email_sent',
        performed_by: session.email,
        user_role: session.role,
        student_name: 'Diagnostic Test',
        details: { to: targetEmail, api_used: sendResult.apiUsed },
      });

      const updatedQuota = await getQuotaStatus();
      return NextResponse.json({
        success: true,
        message: `Diagnostic email delivered via ${sendResult.apiUsed || 'Brevo'}! Quota incremented by 1.`,
        api_used: sendResult.apiUsed,
        quota: updatedQuota,
      });
    }

    return NextResponse.json({ success: false, message: 'Unknown action' }, { status: 400 });
  } catch (err) {
    console.error('Email queue action error:', err);
    return NextResponse.json({ success: false, message: 'Server error' }, { status: 500 });
  }
}
